### ISSUE TITLE
Научиться использовать функциональность "Повторное использование шагов"

### ISSUE THREAD

**Issue by alehinsasha** [oleynikova/final_task#4]
В каталоге features создать каталог, в котором будете накапливать свои библиотечные шаги. Нужно в этом каталоге создать служебную фичу, например:

```
# encoding: utf-8
# language: ru

Функционал: Библиотека шагов
    Как разработчик
    Хочу иметь библиотеку универсальных шагов
    Чтобы вести разработку конфигурации

Контекст:
#   Дано Я открыл новый сеанс TestClient или подключил уже существующий

Сценарий: Универсальные шаги
    И не открылось окно с текстом "Текст"
    И я закрываю клиент тестирования
    И я удаляю все документы вида "СделкаСКлиентом"
    И я загружаю данные для сценария из макета "Сделки"
```

и в ней в одном шаге объединить шаги:
- [Я подготавливаю данные для расчета себестоимости по номенклатуре "Стул"](https://github.com/oleynikova/final_task/blob/master/features/%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%D0%A0%D0%B0%D1%81%D1%87%D0%B5%D1%82%D0%A1%D0%B5%D0%B1%D0%B5%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8%D0%97%D0%B0%D0%9C%D0%B5%D1%81%D1%8F%D1%86.feature#L16)
- [я подготавливаю вспомогательные данные](https://github.com/oleynikova/final_task/blob/master/features/%D0%9F%D1%80%D0%B8%D0%B5%D0%BC%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D0%B0%D0%9E%D1%82%D0%9F%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D1%89%D0%B8%D0%BA%D0%B0.feature#L16)
- [я подготавливаю данные по номенклатуре](https://github.com/oleynikova/final_task/blob/master/features/%D0%9F%D1%80%D0%BE%D0%B4%D0%B0%D0%B6%D0%B0%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D0%B0.feature#L12)

**Comment by oleynikova** [comment]
Задача выполнена
