### ISSUE TITLE
Нужно научиться создавать свои шаги воспроизводящие действия пользователя

### ISSUE THREAD

**Issue by alehinsasha** [oleynikova/final_task#5]
Нужно программно, из обработки проверки поведения, воспроизвести действия пользователя для создания, переименования и удаления. В фиче должен быть один шаг, который:
• если в справочнике нет элемента справочника с наименованием "контрагент2", создает элемент с таким наименованием
• если есть в справочнике элемент с наименованием "контрагент2" переименовывает его в "контрагент1"
• если элементов справочника с наименованием "контрагент1" больше 3, то удаляет все элементы с таким наименованием

т.е. запуская выполнение фичи несколько раз, один и тот же шаг будет работать по разному. В реальности, сценарий линейный и не допускает ветвлений, но в рамках курса пришлось придумать такую задачу, т.к. важно чтобы вы научились создавать свои шаги воспроизводящие действия пользователя.

**Comment by oleynikova** [comment]
В обработке проверки поведения, использую процедуры и функции обработки "РаботаСИнтерфейсом" из репозитория  vanessa-behavior

**Comment by alehinsasha** [comment]
И?)

**Comment by alehinsasha** [comment]
Задача ведь звучит так:

> Нужно научиться создавать свои шаги воспроизводящие действия пользователя

Итак, в рамках этого issue нужно научиться реализовывать свои шаги воспроизведения действий пользователя (в работе пригодиться).  Т.е. ожидаеться, что в фиче будет 1 сценарий и 1 шаг, а в процедуре-проверке этого шага примерно такой код:

```
Если КоличествоЭлементовВСправочникеСНаименованием(<ИмяСправочника>, <ИскомоеНаименование>) = 0 Тогда
   СоздатьЭлементСправочникаСНаименованием(<ИмяСправочника>, <ИскомоеНаименование>);
КонецЕсли;

Функция КоличествоЭлементовВСправочникеСНаименованием(<ИмяСправочника>, <ИскомоеНаименование>)
   КоличествоЭлементов = 0;

   //КонтекстСохраняемый.ТестовоеПриложение.<закрыть все формы>
   //КонтекстСохраняемый.ТестовоеПриложение.<открыть форму списка справочника>
   //КонтекстСохраняемый.ТестовоеПриложение.<перебрать все строки списка и подсчитать количество подходящих элементов>

   Возврат КоличествоЭлементов;
КонецФункции

Процедура СоздатьЭлементСправочникаСНаименованием(<ИмяСправочника>, <ИскомоеНаименование>)
   //КонтекстСохраняемый.ТестовоеПриложение.<закрыть все формы>
   //КонтекстСохраняемый.ТестовоеПриложение.<открыть форму списка справочника>
   //КонтекстСохраняемый.ТестовоеПриложение.<нажать кнопку "Создать">
   //КонтекстСохраняемый.ТестовоеПриложение.<заполнить наименование>
   //КонтекстСохраняемый.ТестовоеПриложение.<нажать кнопку "Записать и закрыть>

КонецПроцедуры
```

Попробуйте сделать это, если будут вопросы - пишите.

**Comment by alehinsasha** [comment]
Используйте vanessa-behavior → Работа с UI → Код проверки поведения.

**Comment by oleynikova** [comment]
Спасибо за подсказку, но смогу выполнить задачу 5 только после 19-го сентября.

**Comment by alehinsasha** [comment]
Хорошо, буду ждать решение после 19-го сентября.

**Comment by oleynikova** [comment]
Изменила обработку. Использовала vanessa-behavior → Работа с UI → Код проверки поведения.

**Comment by alehinsasha** [comment]
Готово
