### ISSUE TITLE
Объединить похожие шаги в один

### ISSUE THREAD

**Issue by alehinsasha** [oleynikova/final_task#6]
[шаг1](https://github.com/oleynikova/final_task/blob/master/features/Libraries/%D0%9F%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%B8%D1%82%D1%8C%D0%94%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5/%D0%9F%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%B8%D1%82%D1%8C%D0%94%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5.feature#L10)

[шаг2](https://github.com/oleynikova/final_task/blob/master/features/Libraries/%D0%9F%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%B8%D1%82%D1%8C%D0%94%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5/%D0%9F%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%B8%D1%82%D1%8C%D0%94%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5.feature#L10)

**Comment by alehinsasha** [comment]
Прошу прощения, начался второй поток и голова идет кругом... С этим issue что-то не получается?

**Comment by oleynikova** [comment]
Ничего страшного.
Вроде я библиотеку создавала в задаче #4

**Comment by alehinsasha** [comment]
Готово
