### ISSUE TITLE
Демонстрация работ заказчику

### ISSUE THREAD

**Issue by alehinsasha** [oleynikova/final_task#7]
**Что нужно сделать**
1. Выгрузить конфигурацию в файлы (конфигуратор → конфигурация → выгрузить конфигурацию в файлы → <ИмяРепозиторияФинальногоЗадания>\src\cf);
2. Закоммитить и отправить во внешний репозиторий.

**Особенности**
- Приступать к выполнению этой задачи нужно после того как закроете все созданные мной issue.
- В публичный внешний репозиторий, нельзя помещать код из типовых конфигураций 1С!

**Comment by alehinsasha** [comment]
Ок, до статуса финалиста вас отделяет только эта задача. Жду выгрузку конфигурации в файлы.

**Comment by oleynikova** [comment]
Выполнила

**Comment by alehinsasha** [comment]
Готово, НО:

> В публичный внешний репозиторий, нельзя помещать код из типовых конфигураций 1С!

в том числе и БСП, аккуратней с этим.

**Comment by oleynikova** [comment]
Да, весь типовой код был удален
